export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const CUSGET_PROFILE_REQUEST = 'CUSGET_PROFILE_REQUEST'
export const CUSGET_PROFILE_SUCCESS = 'CUSGET_PROFILE_SUCCESS'
export const CUSGET_PROFILE_FAIL = 'CUSGET_PROFILE_FAIL'

export const CUSUPDATE_PROFILE_REQUEST = 'CUSUPDATE_PROFILE_REQUEST'
export const CUSUPDATE_PROFILE_SUCCESS = 'CUSUPDATE_PROFILE_SUCCESS'
export const CUSUPDATE_PROFILE_FAIL = 'CUSUPDATE_PROFILE_FAIL'
